INSERT INTO AUTHENTICATION (ID, LOGIN, PASSWORD) VALUES (1001, 'DEV', 'DEV');
INSERT INTO AUTHENTICATION (ID, LOGIN, PASSWORD) VALUES (1002, 'ADMIN', 't@Yoiy45');
INSERT INTO AUTHENTICATION (ID, LOGIN, PASSWORD) VALUES (1003, 'PRO', 'passer');
INSERT INTO AUTHENTICATION (ID, LOGIN, PASSWORD) VALUES (1004, 'CHEF', 'CFA');
